# Generated by Django 2.1.3 on 2019-06-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='pdf_id',
            new_name='fk_pdf_id',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='user_id',
            new_name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='field_id',
        ),
        migrations.RemoveField(
            model_name='pdfform',
            name='pdf_id',
        ),
        migrations.AddField(
            model_name='formfield',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfform',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
