# Generated by Django 2.1.3 on 2019-06-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0003_auto_20190616_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ('field_page_number', 'field_type')},
        ),
        migrations.AlterField(
            model_name='userdata',
            name='field_type',
            field=models.ManyToManyField(default=0, related_name='formfield', to='pdfmerge.FormField'),
        ),
    ]
