# Generated by Django 2.1.3 on 2019-06-17 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0004_auto_20190616_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='field_data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='field_type',
        ),
        migrations.AddField(
            model_name='userdata',
            name='field_type',
            field=models.IntegerField(default=0),
        ),
    ]
