# Generated by Django 2.1.3 on 2019-06-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0005_auto_20190617_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='field_data',
            new_name='field_date',
        ),
    ]
