# Generated by Django 2.1.3 on 2019-06-18 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0006_auto_20190617_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('pdf', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pdfmerge.PDFForm')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='PDFFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_page_number', models.IntegerField(default=0)),
                ('field_x', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('field_y', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('field_x_increment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('field', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pdfmerge.Field')),
                ('pdf', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pdfmerge.PDFForm')),
            ],
            options={
                'ordering': ('field_page_number',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_text', models.CharField(default='', max_length=200)),
                ('field_date', models.DateField()),
                ('field', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pdfmerge.Field')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='fk_pdf_id',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='fk_user_id',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
