# Generated by Django 2.1.3 on 2019-06-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0008_field_field_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='field_type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='field_date',
            field=models.DateField(null=True),
        ),
    ]
