# Generated by Django 2.1.3 on 2019-06-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0009_auto_20190620_1802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('user', 'field')},
        ),
    ]
