# Generated by Django 2.1.3 on 2019-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0010_auto_20190620_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfformfield',
            name='field_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('FULLDATE', 'FULLDATE'), ('DATE', 'DATE'), ('MONTH', 'DATE'), ('YEAR', 'YEAR')], default='NONE', max_length=9),
        ),
    ]
