# Generated by Django 2.1.3 on 2019-06-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0011_pdfformfield_field_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfformfield',
            name='field_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('FULLDATE', 'FULLDATE'), ('DATE', 'DATE'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR'), ('FULLDATE_TEXT_MONTH', 'FULLDATE_TEXT_MONTH')], default='NONE', max_length=20),
        ),
    ]
