# Generated by Django 2.1.3 on 2019-06-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0012_auto_20190623_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfform',
            name='cellSize_X',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='pdfform',
            name='cellSize_Y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='pdfformfield',
            name='font_size',
            field=models.IntegerField(default=0),
        ),
    ]
