# Generated by Django 2.1.3 on 2019-06-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0013_auto_20190623_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfformfield',
            name='field_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('FULLDATE', 'FULLDATE'), ('DATE', 'DATE'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR'), ('FULLDATE_TEXT_MONTH', 'FULLDATE_TEXT_MONTH'), ('CHECK_BOX', 'CHECK_BOX')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfformfield',
            name='font_size',
            field=models.IntegerField(default=12),
        ),
    ]
