# Generated by Django 2.1.3 on 2019-07-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0014_auto_20190623_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfform',
            name='pdf_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
