# Generated by Django 2.1.3 on 2019-07-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0015_pdfform_pdf_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfform',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
