# Generated by Django 2.1.3 on 2019-07-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0017_auto_20190707_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_question',
            field=models.CharField(default='', max_length=300),
        ),
    ]
