# Generated by Django 2.1.3 on 2019-07-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0020_auto_20190711_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='field_choice',
            new_name='field_display',
        ),
    ]
