# Generated by Django 2.1.3 on 2019-07-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0022_auto_20190713_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='field_category',
            new_name='category',
        ),
    ]
