# Generated by Django 2.1.3 on 2019-07-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0023_auto_20190713_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('category', 'category_order', 'field_description')},
        ),
        migrations.AddField(
            model_name='field',
            name='category_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='field',
            name='category',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('DOCUMENT', 'Document'), ('ADDRESS', 'Address')], default='PERSONAL', max_length=20),
        ),
    ]
