# Generated by Django 2.1.3 on 2019-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0024_auto_20190715_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfformfield',
            options={'ordering': ('field_page_number', 'field_index')},
        ),
        migrations.AddField(
            model_name='pdfformfield',
            name='field_index',
            field=models.IntegerField(default=0),
        ),
    ]
