# Generated by Django 2.1.3 on 2019-07-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfmerge', '0025_auto_20190715_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='multichoice_options',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pdfformfield',
            name='field_x_choices',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pdfformfield',
            name='field_y_choices',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_display',
            field=models.CharField(choices=[('NONE', 'NONE'), ('FULLDATE', 'FULLDATE'), ('DATE', 'DATE'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR'), ('FULLDATE_TEXT_MONTH', 'FULLDATE_TEXT_MONTH'), ('CHECK_BOX', 'CHECK_BOX'), ('MULTICHOICE', 'MULTICHOICE')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='field',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='pdfmerge.Field'),
        ),
    ]
